project_id = "wkztzkvjtabfvcdfemby"

[functions.n8n-guest-info]
verify_jwt = false

[functions.trigger-n8n-scraping]
verify_jwt = false

[functions.check-email-exists]
verify_jwt = false

[functions.import-excel-guests]
verify_jwt = false

[functions.chat-guests]
verify_jwt = false

[functions.get-libreto]
verify_jwt = false
