// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-upcoming-guests.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_upcoming_guests_default = defineTool({
  name: "list_upcoming_guests",
  title: "Listar pr\xF3ximos invitados",
  description: "Lista los invitados programados desde hoy en adelante en el calendario de Bla Bla Blu (lunes a jueves).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("M\xE1ximo de invitados a devolver (por defecto 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "No autenticado" }],
        isError: true
      };
    }
    const today = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    const { data, error } = await supabaseForUser(ctx).from("guests").select(
      "id, name, position, topic, day_of_week, week_date, time_slot, recording_status, scheduled_date"
    ).gte("week_date", today).order("week_date", { ascending: true }).order("time_slot", { ascending: true }).limit(limit ?? 25);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { guests: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-guests.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.76.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_guests_default = defineTool2({
  name: "search_guests",
  title: "Buscar invitados",
  description: "Busca invitados por nombre, tema, cargo o contacto de prensa (b\xFAsqueda parcial, sin distinci\xF3n de may\xFAsculas).",
  inputSchema: {
    query: z2.string().trim().min(2).describe("Texto a buscar (m\xEDnimo 2 caracteres)."),
    limit: z2.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const q = query.replace(/[%,]/g, " ");
    const { data, error } = await supabaseForUser2(ctx).from("guests").select(
      "id, name, position, topic, day_of_week, week_date, time_slot, recording_status, press_contact, scheduled_date"
    ).or(
      `name.ilike.%${q}%,topic.ilike.%${q}%,position.ilike.%${q}%,press_contact.ilike.%${q}%`
    ).order("week_date", { ascending: false }).limit(limit ?? 25);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { guests: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-guest.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.76.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_guest_default = defineTool3({
  name: "get_guest",
  title: "Obtener invitado",
  description: "Devuelve todos los datos de un invitado por su id.",
  inputSchema: {
    id: z3.string().uuid().describe("UUID del invitado.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("guests").select("*").eq("id", id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Invitado no encontrado" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { guest: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wkztzkvjtabfvcdfemby";
var mcp_default = defineMcp({
  name: "bla-bla-blu-mcp",
  title: "Bla Bla Blu MCP",
  version: "0.1.0",
  instructions: "Herramientas para consultar el calendario de invitados de Bla Bla Blu (lunes a jueves). Usa 'list_upcoming_guests' para pr\xF3ximos invitados, 'search_guests' para buscar por nombre/tema/cargo, y 'get_guest' para el detalle completo por id.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_upcoming_guests_default, search_guests_default, get_guest_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
