-- Importación única del histórico "BLACK LIST.docx" (38 nombres, Oct 2025).
-- Idempotente: ON CONFLICT sobre name_normalized evita duplicados si se re-ejecuta.

INSERT INTO public.blacklist (name, reason) VALUES
  ('Ana María Sánchez', 'Actriz. No conversa rico, respuesta corta.'),
  ('Juan Pablo Raba', 'Actor. No conversa rico, respuesta corta.'),
  ('Jorge Enrique Abello', 'Actor.'),
  ('Víctor Mallarino', 'Actor, director, productor.'),
  ('Jorge Cao', 'Ya ha venido muchas veces.'),
  ('Adriana Lucía', NULL),
  ('Julio Correal', 'Está en La F.M.'),
  ('Tiberio Cruz', 'No conversa rico, respuesta corta.'),
  ('María Irene Toro', 'Ya ha venido muchas veces.'),
  ('Ana Sofía Henao', 'No conversa rico, respuesta corta.'),
  ('Javier Gardeazabal', 'No conversa rico, respuesta corta.'),
  ('Lina Tejeiro', 'Nos ha dejado plantados como 3 veces.'),
  ('Isabella Santiago', 'No conversa rico, respuesta corta.'),
  ('Cony Camelo', '"Soy muy inteligente y profunda y ustedes no lo son" (dicho por ella).'),
  ('Juan Diego Gómez', 'Nos ha dejado plantados.'),
  ('Tatiana Castro', 'Ya ha venido muchas veces.'),
  ('Carmiña Villegas', 'No conversa rico, respuesta corta.'),
  ('El Tikuna', NULL),
  ('Profesor Salomón', 'Nos ha dejado plantados.'),
  ('Sylvia Ramírez', 'Nos deja en visto en WhatsApp, no le vamos a rogar a nadie.'),
  ('Andrea Venturoli', NULL),
  ('Matador', NULL),
  ('Luis Carlos Vélez', 'Nos ha dejado plantados como 3 veces.'),
  ('María Paula Alonso', 'Empalagosa.'),
  ('Antonio Sanint', 'Comediante.'),
  ('Julián Arango', 'Actor y comediante.'),
  ('Valeria Aguilar', NULL),
  ('Valentina Taguado', NULL),
  ('Suso ''El Paspi''', 'Humorista. Que no da risa.'),
  ('Luisa Vergara', 'Comediante paisa que no da risa.'),
  ('Vicky Berrío', 'Comediante paisa que no da risa.'),
  ('Ibrahim Salem', NULL),
  ('Julio Escallón', 'Humor que nadie entiende.'),
  ('Pamela Ospina', NULL),
  ('Camila Dever', 'Empalagosa. Como para una tercera hora de un primero de enero.'),
  ('Johana Velandia', 'Empalagosa.'),
  ('Culotauro', NULL),
  ('Fuck News', NULL)
ON CONFLICT (name_normalized) DO NOTHING;
